### PR TITLE
Fix scrolling on mac has high delay

### LINKED ISSUE #122: [BUG] Scrolling on mac has high delay
With Version 0.17.0, IntelliJ Idea 2024.2.3 and macOS 14.6.1, the scrolling of the PDF with the built-in touchpad is extremely slow and has a delay. When trying to scroll more than a couple of lines, the PDF viewer is still receiving and handling input seconds after the input stopped. The viewer may even change the direction of the scrolling after the input has stopped. So it is not like the viewer continues to scroll slowly but is actually still handling the queued input events.

Scrolling in all other windows and the editor of IntelliJ works as expected, only the PDF viewer is affected.

### PR DESCRIPTION
**Pull request by znzryb**
Fix #122.

macOS trackpad scrolling in the PDF viewer has severe delay (500-2700ms gaps between scroll updates) and may even reverse direction after input stops, because queued wheel events continue processing. Two root causes identified:

1. **JCEF OSR (Off-Screen Rendering)** synthesizes input events from Swing instead of forwarding native OS events, adding IPC round-trip latency to every scroll.
2. **pdf.js's non-passive `onWheel` listener** (`{ passive: false }`) forces Chromium's compositor thread to wait for the main-thread JS handler to confirm it won't call `preventDefault()` before scrolling — even though the handler completes in <0.1ms, the Swing→Chromium→renderer→JS→back round-trip in JCEF is expensive enough to cause the observed stutter.

### Changes

**`PdfJcefPreviewController.kt`**
- Force `useOsr = false` on macOS so Chromium owns a native window and receives OS events directly (see [IJPL-59459](https://youtrack.jetbrains.com/issue/IJPL-59459)). Other platforms still respect the `pdf.viewer.use.jcef.osr.view` registry flag.

**`Application.kt`**
- Call `PDFViewerApplication.unbindWindowEvents()` to remove all window-level listeners pdf.js registered (including the problematic non-passive `onWheel`). This API is backed by `AbortController` in pdf.js 5.x.
- Re-register only the essential listeners (resize, hashchange, beforeprint, afterprint) — all passive.
- Add a new passive capture-phase wheel handler that handles ctrl+wheel / pinch zoom as a side-effect (calling `increaseScale()` / `decreaseScale()` directly) without `preventDefault()`, which is unnecessary in JCEF's embedded browser context.

### Testing

Tested on macOS with trackpad:
- Two-finger scroll is now smooth with no delay or direction reversal
- Keyboard shortcuts (ctrl+/-) unaffected

### CODE REVIEW

**Comment by znzryb** [comment]
@PHPirates Could you please review this PR? It fixes #122 (macOS scroll delay issue).

**Comment by PHPirates** [comment]
Amazing! Let me first post a pre-release in #122 to get confirmation from someone with a mac to test if this works. I will review this in the next few days

**Comment by znzryb** [comment]
> Amazing! Let me first post a pre-release in #122 to get confirmation from someone with a mac to test if this works. I will review this in the next few days

@PHPirates Thanks for taking the time to review!

File: web-view/viewer/src/jsMain/kotlin/com/firsttimeinforever/intellij/pdf/viewer/application/Application.kt [hunk 1]
```diff
@@ -229,61 +232,105 @@ class Application(private val viewer: ViewerAdapter) {
...
+    // Fix for "Scrolling on mac has high delay" (GH #122, previously #51).
+    //
+    // pdf.js registers a `{ passive: false }` wheel listener (onWheel) for
+    // ctrl/cmd+wheel zoom. A non-passive listener forces the compositor to
+    // round-trip every wheel event through the main thread before scrolling.
+    // In JCEF the Swing→Chromium IPC makes this especially expensive,
+    // causing 500-2700ms scroll gaps on macOS trackpads.
+    //
+    // Fix: call unbindWindowEvents() to remove ALL pdf.js window listeners
+    // (backed by AbortController in pdf.js 5.x), then re-register only the
```
Comment (PHPirates) [inline web-view/viewer/src/jsMain/kotlin/com/firsttimeinforever/intellij/pdf/viewer/application/Application.kt:244]: I just noticed that I broke the dark mode of the sidebar when I updated to pdf.js 5.x in #149, will this still work if I release this based on pdf.js 4.x (reverting my PR)? I did that for 0.17.4-alpha.4 and the comment in #122 seems to suggest it still works.

Otherwise I will quickly try to fix the dark mode issue with the sidebar background color:

Image

Comment (PHPirates) [reply web-view/viewer/src/jsMain/kotlin/com/firsttimeinforever/intellij/pdf/viewer/application/Application.kt:244]: Nevermind, I fixed it in #152. I will just release everything and we'll see if there are any more issues with pdf.js 5 that I missed

**Review by PHPirates — APPROVED** [review]
Great work! I really hope the issue is properly fixed now, that would make a lot of users happy. Will create a release later today
